### ISSUE TITLE
Incorrect API endpoint for Harness OnPrem- pipelines/execution

### ISSUE THREAD

**Issue by travismgibson** [harness/backstage-plugins#67] opened 2023-01-12 00:39 UTC
## Expected Behavior
Expected the correct API Endpoint

## Actual behavior
Endpoint does not work.

## Context
See [code](https://github.com/harness/backstage-plugins/blob/0c4951585e275eb1fe06a16bee69ca08edc3f602/plugins/harness-ci-cd/src/components/ExecutionList/ExecutionList.tsx#L960)

The following is implemented:
```
      const response = await fetch(
        `${await backendBaseUrl}/harness/gateway/pipeline/api/pipelines/execution/v2/summary?${query}`,
        {
          method: 'POST',
        },
      );
```
According to the API spec it should be:
```
      const response = await fetch(
        `${await backendBaseUrl}/harness/gateway/pipeline/api/pipelines/execution/summary?${query}`,
        {
          method: 'POST',
        },
      );

```

**Comment by OrkoHunter** [comment] 2023-01-12 03:02
Hey Travis - thanks for the bug report! @Debanitrkl @sandeepa-kv-jois can you please take a look? If the API endpoints are different for on-prem, we should have separate calls based on whether or not Harness is hosted on `app.harness.io`.

**Comment by Debanitrkl** [comment] 2023-01-12 08:00
Hi @travismgibson, so looks like this API endpoint issue that you were facing is due to the pipeline services not being updated to the latest one on the on-prem version you're using. 
The usage of v2 endpoints, is quite new(~3 months old) and was recently added.
An update to the recent version of on-prem release would solve this issue of yours, marking it as not a bug for plugin side of things.
Thanks

**Closed** 2023-01-13 04:25 UTC
